USE [master]
GO

IF SUSER_ID ( 'HJMiddleware' ) IS NULL BEGIN

	CREATE LOGIN [HJMiddleware] WITH PASSWORD='@ohswe49878!', DEFAULT_DATABASE=[AAD], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
	ALTER LOGIN [HJMiddleware] ENABLE

	USE [AAD]

	CREATE USER [HJMiddleware] FOR LOGIN [HJMiddleware]
	CREATE ROLE [MW_USER]
	ALTER ROLE [MW_USER] ADD MEMBER [HJMiddleware]

END 
